export const CHIEAgentData = [
  {
    title: "Aecc Global - AECC Global",
    phone: "61395713888",
    website: "www.aeccglobal.com",
    addressLine1: null,
    addressLine2: null,
    country: null,
    email: "info@aeccglobal.com",
    agentName: "Aradhana Sethi",
    imageUrl: "/assets/aecc.webp",
  },
  {
    title: "PME Global",
    phone: "6376343036",
    website: null,
    addressLine1: null,
    addressLine2: null,
    country: null,
    email: "admissions@pmeglobal.com.au",
    agentName: "Kanika",
    imageUrl: "/assets/pme.jpg",
  },
  {
    title: "Ultimate Consultancy & Advisory Network",
    phone: "97715348286",
    website: null,
    addressLine1: null,
    addressLine2: null,
    country: null,
    email: "btamang@ucanlogin.com",
    agentName: "Nirajan Panta",
    imageUrl: "/assets/ucan.webp",
  },
  {
    title: "Oxford Education & Visa Services",
    phone: "9.77157E+11",
    website: null,
    addressLine1: null,
    addressLine2: null,
    country: null,
    email: "oxfordacademia.admission@gmail.com",
    agentName: "Prajwol Kafle",
    imageUrl: "/assets/oxford.png",
  },
  {
    title: "Shri Krishna Education & Immigration Consultants",
    phone: "421243060",
    website: "shrikrishnaconsultants.com",
    addressLine1: "MELBOURNE",
    addressLine2: "VICTORIA",
    country: null,
    email: "info@shrikrishnaconsultants.com",
    agentName: "Manish Paul Garg",
    imageUrl: "/assets/shre.jpg",
  },
  {
    title: "Learn Quest Consultancy Services",
    phone: "9.17696E+11",
    website: null,
    addressLine1: null,
    addressLine2: null,
    country: null,
    email: "learnquestcons@gmail.com",
    agentName: "Navjot Singh",
    imageUrl: "/assets/learn.png",
  },
  {
    title: "The Sunshine Immigration Consultancy",
    phone: "-8360506124",
    website: "www.sunshineimmi.com",
    addressLine1: null,
    addressLine2: null,
    country: null,
    email: "australia2@sunshineimmi.com",
    agentName: "Chirag Verma",
    imageUrl: "/assets/sunshine.png",
  },
];
